// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyMatchAnalisis.Data;

#nullable disable

namespace VolleyMatchAnalisis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526083425_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VolleyMatchAnalisis.Models.Gara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AffA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AffB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("G")
                        .HasColumnType("int");

                    b.Property<string>("Impianto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.Property<string>("Ora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Parz_Squadra_A_1")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_2")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_3")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_4")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_5")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_1")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_2")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_3")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_4")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_5")
                        .HasColumnType("int");

                    b.Property<string>("Parziali")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ris")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SquadraA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SquadraB")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Ufficiale")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Gare");
                });

            modelBuilder.Entity("VolleyMatchAnalisis.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aff")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Squadre");
                });
#pragma warning restore 612, 618
        }
    }
}
