// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyMatchAnalisis.Data;

#nullable disable

namespace VolleyMatchAnalisis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VolleyMatchAnalisis.Models.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("Agosto")
                        .HasColumnType("double");

                    b.Property<double?>("Aprile")
                        .HasColumnType("double");

                    b.Property<string>("CAF")
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("longtext");

                    b.Property<string>("CognomeNome")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataFineValidita")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInizioValidita")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPrestitoCambio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataTesseramento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataValidita")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denominazione")
                        .HasColumnType("longtext");

                    b.Property<string>("DenominazioneProvenienza")
                        .HasColumnType("longtext");

                    b.Property<string>("DenominazioneSocietaPrestito")
                        .HasColumnType("longtext");

                    b.Property<double?>("Dicembre")
                        .HasColumnType("double");

                    b.Property<double?>("Febbraio")
                        .HasColumnType("double");

                    b.Property<double?>("Gennaio")
                        .HasColumnType("double");

                    b.Property<double?>("Giugno")
                        .HasColumnType("double");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("longtext");

                    b.Property<double?>("Iscrizione")
                        .HasColumnType("double");

                    b.Property<string>("LocalitaNascita")
                        .HasColumnType("longtext");

                    b.Property<string>("LocalitaResidenza")
                        .HasColumnType("longtext");

                    b.Property<double?>("Luglio")
                        .HasColumnType("double");

                    b.Property<double?>("Maggio")
                        .HasColumnType("double");

                    b.Property<double?>("Marzo")
                        .HasColumnType("double");

                    b.Property<string>("Matricola")
                        .HasColumnType("longtext");

                    b.Property<int?>("MesiValidita")
                        .HasColumnType("int");

                    b.Property<string>("ModTipoAttivita")
                        .HasColumnType("longtext");

                    b.Property<double?>("Novembre")
                        .HasColumnType("double");

                    b.Property<double?>("Ottobre")
                        .HasColumnType("double");

                    b.Property<string>("ProvinciaNascita")
                        .HasColumnType("longtext");

                    b.Property<string>("ProvinciaResidenza")
                        .HasColumnType("longtext");

                    b.Property<string>("Sesso")
                        .HasColumnType("longtext");

                    b.Property<double?>("Settembre")
                        .HasColumnType("double");

                    b.Property<string>("SocietaAppartenenza")
                        .HasColumnType("longtext");

                    b.Property<string>("SocietaPrestito")
                        .HasColumnType("longtext");

                    b.Property<string>("SocietaProvenienza")
                        .HasColumnType("longtext");

                    b.Property<string>("SocietaTesserata")
                        .HasColumnType("longtext");

                    b.Property<string>("Stagione")
                        .HasColumnType("longtext");

                    b.Property<string>("Tessera")
                        .HasColumnType("longtext");

                    b.Property<string>("TesseraSV")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Atleti");
                });

            modelBuilder.Entity("VolleyMatchAnalisis.Models.Gara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AffA")
                        .HasColumnType("longtext");

                    b.Property<string>("AffB")
                        .HasColumnType("longtext");

                    b.Property<string>("Cod")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("G")
                        .HasColumnType("int");

                    b.Property<string>("Impianto")
                        .HasColumnType("longtext");

                    b.Property<string>("Localita")
                        .HasColumnType("longtext");

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.Property<string>("Ora")
                        .HasColumnType("longtext");

                    b.Property<int?>("Parz_Squadra_A_1")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_2")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_3")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_4")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_A_5")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_1")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_2")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_3")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_4")
                        .HasColumnType("int");

                    b.Property<int?>("Parz_Squadra_B_5")
                        .HasColumnType("int");

                    b.Property<string>("Parziali")
                        .HasColumnType("longtext");

                    b.Property<string>("Ris")
                        .HasColumnType("longtext");

                    b.Property<string>("SquadraA")
                        .HasColumnType("longtext");

                    b.Property<string>("SquadraB")
                        .HasColumnType("longtext");

                    b.Property<bool>("Ufficiale")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Gare");
                });

            modelBuilder.Entity("VolleyMatchAnalisis.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beneficiario")
                        .HasColumnType("longtext");

                    b.Property<string>("Causale")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataBonifico")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Elaborato")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Importo")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Pagamenti");
                });

            modelBuilder.Entity("VolleyMatchAnalisis.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aff")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Squadre");
                });
#pragma warning restore 612, 618
        }
    }
}
